apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-user-app
  namespace: fake-user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-user-app
  template:
    metadata:
      labels:
        app: fake-user-app
    spec:
      containers:
        - name: app
          image: hamoood5210/fake-user-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://my-postgres-db-2:5432/fake_user_app
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: fake-user-app
  namespace: fake-user-app
spec:
  selector:
    app: fake-user-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080